import React from 'react';
import {
  Container,
  Typography,
  Button,
  Box,
  Grid,
  Card,
  CardContent,
  CardActions,
  useTheme,
  useMediaQuery,
} from '@mui/material';
import {
  Restaurant,
  TrendingUp,
  Speed,
  Security,
  SmartToy,
  GetApp,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

const Landing: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  const features = [
    {
      icon: <SmartToy sx={{ fontSize: 40, color: '#2e7d32' }} />,
      title: 'AI-Powered Plans',
      description: 'Get personalized diet plans generated by advanced AI technology based on your unique profile and goals.',
    },
    {
      icon: <Restaurant sx={{ fontSize: 40, color: '#2e7d32' }} />,
      title: 'Diverse Cuisines',
      description: 'Enjoy meals from various cultures and cuisines, tailored to your dietary preferences and restrictions.',
    },
    {
      icon: <TrendingUp sx={{ fontSize: 40, color: '#2e7d32' }} />,
      title: 'Track Progress',
      description: 'Monitor your nutrition intake and progress towards your health and fitness goals with detailed analytics.',
    },
    {
      icon: <Speed sx={{ fontSize: 40, color: '#2e7d32' }} />,
      title: 'Quick & Easy',
      description: 'Generate comprehensive weekly meal plans in seconds with recipes, instructions, and shopping lists.',
    },
    {
      icon: <Security sx={{ fontSize: 40, color: '#2e7d32' }} />,
      title: 'Safe & Secure',
      description: 'Your personal health data is protected with enterprise-grade security and privacy measures.',
    },
    {
      icon: <GetApp sx={{ fontSize: 40, color: '#2e7d32' }} />,
      title: 'Export PDF',
      description: 'Download your meal plans as beautiful PDF documents to print or share with nutritionists.',
    },
  ];

  return (
    <Box>
      {/* Hero Section */}
      <Box
        sx={{
          background: 'linear-gradient(135deg, #2e7d32 0%, #4caf50 100%)',
          color: 'white',
          py: { xs: 8, md: 12 },
          textAlign: 'center',
        }}
      >
        <Container maxWidth="lg">
          <Typography
            variant={isMobile ? 'h3' : 'h1'}
            component="h1"
            gutterBottom
            sx={{ fontWeight: 700, mb: 3 }}
          >
            Your Personalized Diet Planner
          </Typography>
          <Typography
            variant={isMobile ? 'h6' : 'h4'}
            component="h2"
            sx={{ mb: 4, opacity: 0.9, fontWeight: 300 }}
          >
            AI-powered nutrition plans tailored to your goals, preferences, and lifestyle
          </Typography>
          <Box sx={{ mt: 4 }}>
            {user ? (
              <Button
                variant="contained"
                size="large"
                onClick={() => navigate('/dashboard')}
                sx={{
                  bgcolor: 'white',
                  color: '#2e7d32',
                  px: 4,
                  py: 1.5,
                  fontSize: '1.1rem',
                  fontWeight: 600,
                  '&:hover': {
                    bgcolor: '#f5f5f5',
                  },
                }}
              >
                Go to Dashboard
              </Button>
            ) : (
              <Box sx={{ display: 'flex', gap: 2, justifyContent: 'center', flexWrap: 'wrap' }}>
                <Button
                  variant="contained"
                  size="large"
                  onClick={() => navigate('/register')}
                  sx={{
                    bgcolor: 'white',
                    color: '#2e7d32',
                    px: 4,
                    py: 1.5,
                    fontSize: '1.1rem',
                    fontWeight: 600,
                    '&:hover': {
                      bgcolor: '#f5f5f5',
                    },
                  }}
                >
                  Get Started Free
                </Button>
                <Button
                  variant="outlined"
                  size="large"
                  onClick={() => navigate('/login')}
                  sx={{
                    borderColor: 'white',
                    color: 'white',
                    px: 4,
                    py: 1.5,
                    fontSize: '1.1rem',
                    fontWeight: 600,
                    '&:hover': {
                      borderColor: '#f5f5f5',
                      bgcolor: 'rgba(255, 255, 255, 0.1)',
                    },
                  }}
                >
                  Sign In
                </Button>
              </Box>
            )}
          </Box>
        </Container>
      </Box>

      {/* Features Section */}
      <Container maxWidth="lg" sx={{ py: 8 }}>
        <Typography
          variant="h2"
          component="h2"
          textAlign="center"
          gutterBottom
          sx={{ mb: 6, fontWeight: 600, color: '#2e7d32' }}
        >
          Why Choose Our Diet Planner?
        </Typography>
        <Grid container spacing={4}>
          {features.map((feature, index) => (
            <Grid item xs={12} sm={6} md={4} key={index}>
              <Card
                sx={{
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  textAlign: 'center',
                  transition: 'transform 0.2s',
                  '&:hover': {
                    transform: 'translateY(-5px)',
                    boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
                  },
                }}
              >
                <CardContent sx={{ flexGrow: 1, p: 3 }}>
                  <Box sx={{ mb: 2 }}>
                    {feature.icon}
                  </Box>
                  <Typography variant="h5" component="h3" gutterBottom sx={{ fontWeight: 600 }}>
                    {feature.title}
                  </Typography>
                  <Typography variant="body1" color="text.secondary">
                    {feature.description}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>

      {/* How It Works Section */}
      <Box sx={{ bgcolor: '#f8f9fa', py: 8 }}>
        <Container maxWidth="lg">
          <Typography
            variant="h2"
            component="h2"
            textAlign="center"
            gutterBottom
            sx={{ mb: 6, fontWeight: 600, color: '#2e7d32' }}
          >
            How It Works
          </Typography>
          <Grid container spacing={4} sx={{ textAlign: 'center' }}>
            <Grid item xs={12} md={4}>
              <Box sx={{ mb: 2 }}>
                <Typography
                  variant="h3"
                  sx={{
                    color: '#2e7d32',
                    fontWeight: 700,
                    fontSize: '3rem',
                    mb: 2,
                  }}
                >
                  1
                </Typography>
              </Box>
              <Typography variant="h5" gutterBottom sx={{ fontWeight: 600 }}>
                Create Your Profile
              </Typography>
              <Typography variant="body1" color="text.secondary">
                Tell us about your age, weight, height, goals, and dietary preferences.
              </Typography>
            </Grid>
            <Grid item xs={12} md={4}>
              <Box sx={{ mb: 2 }}>
                <Typography
                  variant="h3"
                  sx={{
                    color: '#2e7d32',
                    fontWeight: 700,
                    fontSize: '3rem',
                    mb: 2,
                  }}
                >
                  2
                </Typography>
              </Box>
              <Typography variant="h5" gutterBottom sx={{ fontWeight: 600 }}>
                AI Generates Your Plan
              </Typography>
              <Typography variant="body1" color="text.secondary">
                Our AI creates a personalized weekly meal plan with recipes and nutritional information.
              </Typography>
            </Grid>
            <Grid item xs={12} md={4}>
              <Box sx={{ mb: 2 }}>
                <Typography
                  variant="h3"
                  sx={{
                    color: '#2e7d32',
                    fontWeight: 700,
                    fontSize: '3rem',
                    mb: 2,
                  }}
                >
                  3
                </Typography>
              </Box>
              <Typography variant="h5" gutterBottom sx={{ fontWeight: 600 }}>
                Follow & Track Progress
              </Typography>
              <Typography variant="body1" color="text.secondary">
                Follow your meal plan, make adjustments, and track your progress towards your goals.
              </Typography>
            </Grid>
          </Grid>
        </Container>
      </Box>

      {/* CTA Section */}
      <Box sx={{ bgcolor: '#2e7d32', color: 'white', py: 8 }}>
        <Container maxWidth="md" sx={{ textAlign: 'center' }}>
          <Typography variant="h3" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
            Ready to Transform Your Nutrition?
          </Typography>
          <Typography variant="h6" sx={{ mb: 4, opacity: 0.9 }}>
            Join thousands of users who have achieved their health goals with our AI-powered diet plans.
          </Typography>
          {!user && (
            <Button
              variant="contained"
              size="large"
              onClick={() => navigate('/register')}
              sx={{
                bgcolor: 'white',
                color: '#2e7d32',
                px: 6,
                py: 2,
                fontSize: '1.2rem',
                fontWeight: 600,
                '&:hover': {
                  bgcolor: '#f5f5f5',
                },
              }}
            >
              Start Your Free Plan Today
            </Button>
          )}
        </Container>
      </Box>

      {/* Footer */}
      <Box sx={{ bgcolor: '#1b5e20', color: 'white', py: 4 }}>
        <Container maxWidth="lg">
          <Typography variant="body2" textAlign="center" sx={{ opacity: 0.8 }}>
            © 2024 Diet Planner. All rights reserved. | Powered by AI Technology
          </Typography>
        </Container>
      </Box>
    </Box>
  );
};

export default Landing;
